name = "Siegert"
uuid = "83e9d540-1928-48ba-9c41-febf9f69153f"
version = "0.1.0"

[deps]
Jacobi = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Jacobi = "0.7"
LinearAlgebra = "1.11.0"
SpecialFunctions = "2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
